# Generated by Django 2.1 on 2019-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='add_tiem',
            new_name='add_time',
        ),
    ]
